language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

before_script:
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
